tatami-policy(8)

# NAME

tatami policy - show repository policy for packages

# SYNOPSIS

*tatami policy* [<_options_>...] _packages_...

# DESCRIPTION

*tatami policy* shows tatami's repository policy for the specified packages. It
prints matching packages and their versions available from configured
repositories (see *tatami-repositories*(5)), sorted by ascending version.

# OPTIONS

The global options (see *tatami*(8)) and query options (see *tatami-query*(8))
are supported.
